# Generated by Django 3.2.8 on 2021-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_choice', models.CharField(choices=[('C', 'Carrier'), ('MF', 'Month From'), ('MT', 'Month To'), ('Y', 'Year')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('filterType', models.ManyToManyField(related_name='_scrape_years_filterType_+', through='scrape.Filters', to='scrape.Years')),
            ],
        ),
        migrations.CreateModel(
            name='MonthTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('filterType', models.ManyToManyField(related_name='_scrape_monthto_filterType_+', through='scrape.Filters', to='scrape.MonthTo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('filterType', models.ManyToManyField(related_name='_scrape_monthfrom_filterType_+', through='scrape.Filters', to='scrape.MonthFrom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('filterType', models.ManyToManyField(related_name='_scrape_carriers_filterType_+', through='scrape.Filters', to='scrape.Carriers')),
            ],
        ),
    ]
