# Generated by Django 3.2.8 on 2021-10-15 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOOLS',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('urlNAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateResponse',
            fields=[
                ('tools_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrape.tools')),
            ],
            bases=(django.views.generic.base.TemplateResponseMixin, 'scrape.tools'),
        ),
        migrations.AddIndex(
            model_name='tools',
            index=models.Index(fields=['urlNAME'], name='urlNAME_idx'),
        ),
    ]
