# Generated by Django 3.2.8 on 2021-10-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriers',
            name='filterType',
        ),
        migrations.RemoveField(
            model_name='monthfrom',
            name='filterType',
        ),
        migrations.RemoveField(
            model_name='monthto',
            name='filterType',
        ),
        migrations.RemoveField(
            model_name='years',
            name='filterType',
        ),
    ]
