# Generated by Django 3.2.8 on 2021-10-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrape', '0002_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOOLS',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('urlNAME', models.CharField(max_length=50)),
            ],
        ),
    ]
