# Generated by Django 3.2.8 on 2021-10-15 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateResponse',
            fields=[
                ('tools_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrape.tools')),
            ],
            bases=(django.views.generic.base.TemplateResponseMixin, 'scrape.tools'),
        ),
    ]
